/**********************************************************************

	--- Qt Architect generated file ---

	File: qtProtekData.h
	Last generated: Tue Jun 22 14:44:33 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef qtProtekData_included
#define qtProtekData_included

#include <qwidget.h>
#include <qtimer.h>
//#include <qpushbt.h>
#include <qpushbutton.h>
#include <qobject.h>
#include <qlabel.h>
#include <qframe.h>
#include <qapplication.h>
//#include <qlayout.h>
//#include <qpainter.h>
#include <qlineedit.h> 

#include "ClsKhepDisp.hpp"


using namespace std;

class qtProtekData : public QWidget
{
    Q_OBJECT

public:

    qtProtekData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~qtProtekData();
    QTimer * timerSerial;
    QLabel* lblFilename;
    QLineEdit * leFilename;  

private:
    QPushButton* qtarch_btnStart;
    ClsKhepDisp *clsKhepDisp;

    int iTime;
    
    
public slots:
    void DoKhepera();
    void GraphClicked( int iPassBack );


protected slots:


protected:

};


#endif // qtProtekData_included


