######################################################################
# Automatically generated by qmake (1.06c) Mon Mar 15 16:54:03 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += SimpleTransform.cpp
