######################################################################
# Automatically generated by qmake (1.07a) Wed Feb 9 01:09:30 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ClsSystemDB.h CmdBuildImpl.h
INTERFACES += CmdBuild.ui
SOURCES += ClsSystemDB.cpp CmdBuildImpl.cpp main.cpp
