######################################################################
# Automatically generated by qmake (1.07a) Tue Feb 8 16:29:01 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += client.h
SOURCES += main.cpp
