######################################################################
# Automatically generated by qmake (1.07a) Fri Feb 11 12:42:04 2005
######################################################################

TEMPLATE = app
DEPENDPATH += mail
INCLUDEPATH += .

# Input
HEADERS += iqrCRWimpl.h process.h smtp.h
INTERFACES += iqrCRW.ui
SOURCES += iqrCRWimpl.cpp main.cpp process.cpp smtp.cpp 
